"""create insurance management tables

Revision ID: 33375c0692fa
Revises: e77c88dbd3b1
Create Date: 2026-09-01 10:36:53.209031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33375c0692fa'
down_revision: Union[str, Sequence[str], None] = 'e77c88dbd3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('identification_number', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_identification_number'), 'customers', ['identification_number'], unique=True)
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=150), nullable=False),
    sa.Column('plan_type', sa.Enum('LIFE', 'HEALTH', 'VEHICLE', 'PROPERTY', 'TRAVEL', name='plantype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('eligibility_age_min', sa.Integer(), nullable=False),
    sa.Column('eligibility_age_max', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='planstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_id'), 'insurance_plans', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_plans_plan_name'), 'insurance_plans', ['plan_name'], unique=True)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('policy_status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED', name='policystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('identification_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_id'), 'beneficiaries', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number', name='uq_claim_claim_number'),
    sa.UniqueConstraint('policy_id', 'incident_date', name='uq_claim_policy_incident')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claims_customer_id'), 'claims', ['customer_id'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_policy_id'), 'claims', ['policy_id'], unique=False)
    op.create_table('premium_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('premium_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_payments_customer_id'), 'premium_payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_premium_payments_id'), 'premium_payments', ['id'], unique=False)
    op.create_index(op.f('ix_premium_payments_policy_id'), 'premium_payments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_premium_payments_transaction_id'), 'premium_payments', ['transaction_id'], unique=True)
    op.create_table('claim_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('assessor_id', sa.Integer(), nullable=False),
    sa.Column('eligible_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('assessment_notes', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_assessments_assessor_id'), 'claim_assessments', ['assessor_id'], unique=False)
    op.create_index(op.f('ix_claim_assessments_claim_id'), 'claim_assessments', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claim_assessments_id'), 'claim_assessments', ['id'], unique=False)
    op.create_table('claim_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_documents_claim_id'), 'claim_documents', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_documents_id'), 'claim_documents', ['id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('settlement_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', name='uq_settlement_claim_id'),
    sa.UniqueConstraint('payment_reference', name='uq_settlement_payment_reference')
    )
    op.create_index(op.f('ix_settlements_claim_id'), 'settlements', ['claim_id'], unique=False)
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_index(op.f('ix_settlements_payment_reference'), 'settlements', ['payment_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_payment_reference'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_claim_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_claim_documents_id'), table_name='claim_documents')
    op.drop_index(op.f('ix_claim_documents_claim_id'), table_name='claim_documents')
    op.drop_table('claim_documents')
    op.drop_index(op.f('ix_claim_assessments_id'), table_name='claim_assessments')
    op.drop_index(op.f('ix_claim_assessments_claim_id'), table_name='claim_assessments')
    op.drop_index(op.f('ix_claim_assessments_assessor_id'), table_name='claim_assessments')
    op.drop_table('claim_assessments')
    op.drop_index(op.f('ix_premium_payments_transaction_id'), table_name='premium_payments')
    op.drop_index(op.f('ix_premium_payments_policy_id'), table_name='premium_payments')
    op.drop_index(op.f('ix_premium_payments_id'), table_name='premium_payments')
    op.drop_index(op.f('ix_premium_payments_customer_id'), table_name='premium_payments')
    op.drop_table('premium_payments')
    op.drop_index(op.f('ix_claims_policy_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_customer_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_beneficiaries_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_insurance_plans_plan_name'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_customers_identification_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
