"""create notifications table

Revision ID: a14949ea3301
Revises: fe0445f3cf5c
Create Date: 2026-09-01 15:33:56.849124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14949ea3301'
down_revision: Union[str, Sequence[str], None] = 'fe0445f3cf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('policy_renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_policy_id', sa.Integer(), nullable=False),
    sa.Column('new_policy_id', sa.Integer(), nullable=False),
    sa.Column('previous_start_date', sa.Date(), nullable=False),
    sa.Column('previous_end_date', sa.Date(), nullable=False),
    sa.Column('new_start_date', sa.Date(), nullable=False),
    sa.Column('new_end_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.DateTime(), nullable=False),
    sa.Column('renewal_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['new_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['previous_policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('new_policy_id', name='uq_policy_renewal_new_policy'),
    sa.UniqueConstraint('previous_policy_id', name='uq_policy_renewal_previous_policy')
    )
    op.create_index(op.f('ix_policy_renewals_id'), 'policy_renewals', ['id'], unique=False)
    op.create_index(op.f('ix_policy_renewals_new_policy_id'), 'policy_renewals', ['new_policy_id'], unique=False)
    op.create_index(op.f('ix_policy_renewals_previous_policy_id'), 'policy_renewals', ['previous_policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_renewals_previous_policy_id'), table_name='policy_renewals')
    op.drop_index(op.f('ix_policy_renewals_new_policy_id'), table_name='policy_renewals')
    op.drop_index(op.f('ix_policy_renewals_id'), table_name='policy_renewals')
    op.drop_table('policy_renewals')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
